/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/space_station_3/scene.gltf
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-3-a7a6ad10261149cab31aa394bfcf8940
Title: Space Station 3
*/
import * as THREE from "three";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import React, { useRef, useEffect, useLayoutEffect } from "react";

// export const FLOOR_HEIGHT = 2.3;
// export const NB_FLOORS = 3;

const Model = ({ ...props }) => {
  const { nodes, materials, animations } = useGLTF(
    "./models/space_station_3/scene.gltf"
  );
  const group = useRef();
  const scroll = useScroll();
  const tl = useRef();
  const { actions, names } = useAnimations(animations, group);

  // const extras = {
  //   receiveShadow: true,
  //   castShadow: true,
  //   "material-envMapIntensity": 0.2,
  // };

  // useFrame(() => {
  //   tl.current.seek(scroll.offset * tl.current.duration());
  // });

  // useLayoutEffect(() => {
  //   tl.current = gsap.timeline();
  //   tl.current.to(
  //     ref.current.position,
  //     {
  //       duration: 2,
  //       y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
  //     },
  //     0
  //   );
  // }, []);

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut" },
    });

    tl.current
      .to(group.current.rotation, { y: -5 }, 2)
      .to(group.current.position, { x: 5 }, 2)

      .to(group.current.rotation, { y: 5 }, 6)
      .to(group.current.position, { x: -5 }, 6)

      .to(group.current.rotation, { y: -7 }, 11)
      .to(group.current.rotation, { x: 7 }, 11)
      // .to(group.current.position, { x: 0 }, 11)

      .to(group.current.rotation, { y: -5 }, 13)
      .to(group.current.position, { x: 5 }, 13)
      .to(group.current.position, { x: 0 }, 13)

      .to(group.current.rotation, { y: 5 }, 16)
      .to(group.current.position, { x: -5 }, 16)

      .to(group.current.rotation, { y: 0 }, 20)
      .to(group.current.rotation, { x: 0 }, 20);
  });

  useEffect(() => {
    actions[names[0]].reset().fadeIn(3).play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-2.04, -0.21, -0.06]}
          scale={4.7}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="SpaceStation_low_0">
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.spacestation_main2}
                />
              </group>
              <group name="SpaceStation001_low_1">
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.spacestation_smalllights}
                />
              </group>
              <group name="SpaceStation002_low_2">
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.spacestation_main2}
                />
              </group>
              <group name="SpaceStation003_low_3">
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.spacestation_main2}
                />
              </group>
              <group name="SpaceStation004_low_4">
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.spacestation_main}
                />
              </group>
              <group name="SpaceStation005_low_5">
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials.spacestation_main}
                />
              </group>
              <group
                name="SpaceStation006_low_6"
                rotation={[Math.PI, -0.54, Math.PI]}
              >
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials.spacestation_main}
                />
              </group>
              <group name="SpaceStation007_low_7">
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials.spacestation_main}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Model;

useGLTF.preload("./models/space_station_3/scene.gltf");
